name: Camagru

services:
  server:
    build:
      context: ./Services/Server
    image: camagru/server
    container_name: nginx
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - test
      - user
      - media
      - mail
      - interaction
      - notification
    networks:
      - camagru
    volumes:
      - ./Services/volumes/volumemedia:/app/volume

  test:
    build:
      context: ./Services/service_test
    image: camagru/php_test
    container_name: app_test
    networks:
      - camagru

  user:
    build:
      context: ./Services
      dockerfile: User/Dockerfile
    image: camagru/user
    container_name: app_user
    networks:
      - camagru

  media:
    build:
      context: ./Services
      dockerfile: Media/Dockerfile
    image: camagru/media
    container_name: app_media
    networks:
      - camagru
    volumes:
      - ./Services/volumes/volumemedia:/app/volume

  mail:
    build:
      context: ./Services
      dockerfile: Mail/Dockerfile
    image: camagru/mail
    container_name: app_mail
    networks:
        - camagru

  interaction:
    build:
      context: ./Services
      dockerfile: Interaction/Dockerfile
    image: camagru/interaction
    container_name: app_interaction
    networks:
      - camagru

  notification:
    build:
      context: ./Services
      dockerfile: Notification/Dockerfile
    image: camagru/notification
    container_name: app_notification
    networks:
      - camagru

  user_db:
    image: postgres:16
    networks:
      - camagru
    environment: 
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    volumes:
      - user_db_data:/var/lib/postgresql/data
      - ./Services/db/user/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  media_db:
    image: postgres:16
    networks:
      - camagru
    volumes:
      - media_db_data:/var/lib/postgresql/data
      
  interaction_db:
    image: postgres:16
    networks:
      - camagru
    volumes:
      - interaction_db_data:/var/lib/postgresql/data
     
  redis:
    image: redis:7
    container_name: camagru_redis
    networks:
      - camagru

volumes:
  user_db_data:
  media_db_data:
  interaction_db_data:

networks:
  camagru:
    name: camagru
