server {
    listen              443 ssl;
    ssl_certificate /etc/nginx/ssl/camagru.crt;
    ssl_certificate_key /etc/nginx/ssl/camagru.key;
    location /{
        root srcs/;
        index html/index.html;
    }
    location /service_test{
        proxy_pass http://app:8081/;
    }
}
