server {
    listen              443 ssl;
    ssl_certificate /etc/nginx/ssl/camagru.crt;
    ssl_certificate_key /etc/nginx/ssl/camagru.key;
    client_max_body_size 20M;
    location /{
        root srcs/;
        index html/index.html;
    }
    location /service_test{
        proxy_pass http://app_php:8081/;
    }
    location /images/ {
    alias /app/volume/;
    autoindex off;
    }
}

server {
    listen 80;
    server_name localhost;

    location / {
        return 301 https://$host:4433$request_uri;
    }
}